#!/bin/bash

# Model A
echo "Model A ----------------------------------------"
ipython --pdb -- no_box_attack.py --dataset mnist --namestr="A-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelA --adv_models modelA_ens modelD modelB modelC --source_arch ens_adv --type 0 --eval_freq 1 --transfer --train_on_list --wandb &
ipython --pdb -- no_box_attack.py --dataset mnist --namestr="A-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelA --adv_models modelA_ens modelD modelB modelC --source_arch ens_adv --type 0 --eval_freq 1 --transfer --train_on_list --wandb &
ipython --pdb -- no_box_attack.py --dataset mnist --namestr="A-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelA --adv_models modelA_ens modelD modelB modelC --source_arch ens_adv --type 0 --eval_freq 1 --transfer --train_on_list --wandb &
ipython --pdb -- no_box_attack.py --dataset mnist --namestr="A-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelA --adv_models modelA_ens modelD modelB modelC --source_arch ens_adv --type 0 --eval_freq 1 --transfer --train_on_list --wandb &
ipython --pdb -- no_box_attack.py --dataset mnist --namestr="A-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelA --adv_models modelA_ens modelD modelB modelC --source_arch ens_adv --type 0 --eval_freq 1 --transfer --train_on_list --wandb &

# Model B
#echo "Model B ----------------------------------------"
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="B-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelB --adv_models modelB_ens modelA modelD modelC --source_arch ens_adv --type 1 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="B-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelB --adv_models modelB_ens modelA modelD modelC --source_arch ens_adv --type 1 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="B-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelB --adv_models modelB_ens modelA modelD modelC --source_arch ens_adv --type 1 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="B-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelB --adv_models modelB_ens modelA modelD modelC --source_arch ens_adv --type 1 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="B-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelB --adv_models modelB_ens modelA modelD modelC --source_arch ens_adv --type 1 --eval_freq 1 --transfer --train_on_list --wandb &

## Model C
#echo "Model C ----------------------------------------"
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="C-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelC --adv_models modelC_ens modelA modelB modelD --source_arch ens_adv --type 2 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="C-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelC --adv_models modelC_ens modelA modelB modelD --source_arch ens_adv --type 2 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="C-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelC --adv_models modelC_ens modelA modelB modelD --source_arch ens_adv --type 2 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="C-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelC --adv_models modelC_ens modelA modelB modelD --source_arch ens_adv --type 2 --eval_freq 1 --transfer --train_on_list --wandb &
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="C-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelC --adv_models modelC_ens modelA modelB modelD --source_arch ens_adv --type 2 --eval_freq 1 --transfer --train_on_list --wandb &

## Model D
#echo "Model D ----------------------------------------"
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="D-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelD --adv_models modelD_ens modelA modelB modelC --source_arch ens_adv --type 3 --eval_freq 1 --transfer --train_on_list --wandb
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="D-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelD --adv_models modelD_ens modelA modelB modelC --source_arch ens_adv --type 3 --eval_freq 1 --transfer --train_on_list --wandb
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="D-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelD --adv_models modelD_ens modelA modelB modelC --source_arch ens_adv --type 3 --eval_freq 1 --transfer --train_on_list --wandb
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="D-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelD --adv_models modelD_ens modelA modelB modelC --source_arch ens_adv --type 3 --eval_freq 1 --transfer --train_on_list --wandb
#ipython --pdb -- no_box_attack.py --dataset mnist --namestr="D-Ens Mnist eps 0.3" --perturb_loss Linf --epsilon=0.3 --attack_ball Linf --batch_size 256 --test_batch_size 64 --attack_epochs 150 --extragradient --lr 1e-3 --lr_model 1e-3 --max_iter 20 --pgd_on_critic --attack_loss cross_entropy --model CondGen --num_test_samples 256 --dir_test_models ../ --command train --model_name modelD --adv_models modelD_ens modelA modelB modelC --source_arch ens_adv --type 3 --eval_freq 1 --transfer --train_on_list --wandb
